# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(932, 742)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(932, 742))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background-color: #f0f8ff;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #333333;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #E74C3C;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #3498DB;\n"
"    border-radius: 8px;\n"
"    margin-top: 1ex;\n"
"    padding-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px 0 5px;\n"
"    color: #3498DB;\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.orgImg = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orgImg.sizePolicy().hasHeightForWidth())
        self.orgImg.setSizePolicy(sizePolicy)
        self.orgImg.setMinimumSize(QtCore.QSize(0, 320))
        self.orgImg.setAutoFillBackground(False)
        self.orgImg.setStyleSheet("background-color: white;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 4px;")
        self.orgImg.setText("")
        self.orgImg.setAlignment(QtCore.Qt.AlignCenter)
        self.orgImg.setObjectName("orgImg")
        self.verticalLayout_3.addWidget(self.orgImg)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #2ECC71;\n"
"    border-radius: 8px;\n"
"    margin-top: 1ex;\n"
"    padding-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px 0 5px;\n"
"    color: #2ECC71;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TransImg = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TransImg.sizePolicy().hasHeightForWidth())
        self.TransImg.setSizePolicy(sizePolicy)
        self.TransImg.setMinimumSize(QtCore.QSize(0, 320))
        self.TransImg.setStyleSheet("background-color: white;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 4px;")
        self.TransImg.setText("")
        self.TransImg.setAlignment(QtCore.Qt.AlignCenter)
        self.TransImg.setObjectName("TransImg")
        self.verticalLayout_4.addWidget(self.TransImg)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("QFrame#frame_3 {\n"
"    background-color: #F5F5F5;\n"
"    border-radius: 8px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #333333;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setMinimumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    background-color: white;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.styleLb = QtWidgets.QLabel(self.frame_3)
        self.styleLb.setMinimumSize(QtCore.QSize(160, 160))
        self.styleLb.setMaximumSize(QtCore.QSize(160, 160))
        self.styleLb.setStyleSheet("background-color: white;\n"
"border: 1px solid #CCCCCC;\n"
"border-radius: 4px;")
        self.styleLb.setText("")
        self.styleLb.setScaledContents(True)
        self.styleLb.setAlignment(QtCore.Qt.AlignCenter)
        self.styleLb.setObjectName("styleLb")
        self.verticalLayout_7.addWidget(self.styleLb)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chageBtn = QtWidgets.QPushButton(self.frame_3)
        self.chageBtn.setMinimumSize(QtCore.QSize(120, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.chageBtn.setFont(font)
        self.chageBtn.setStyleSheet("QPushButton#chageBtn {\n"
"    background-color: #3498DB;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#chageBtn:hover {\n"
"    background-color: #2980B9;\n"
"}\n"
"QPushButton#chageBtn:pressed {\n"
"    background-color: #1F618D;\n"
"}")
        self.chageBtn.setObjectName("chageBtn")
        self.verticalLayout_8.addWidget(self.chageBtn)
        self.saveBtn = QtWidgets.QPushButton(self.frame_3)
        self.saveBtn.setMinimumSize(QtCore.QSize(120, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("QPushButton#saveBtn {\n"
"    background-color: #2ECC71;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#saveBtn:hover {\n"
"    background-color: #27AE60;\n"
"}\n"
"QPushButton#saveBtn:pressed {\n"
"    background-color: #1E8449;\n"
"}")
        self.saveBtn.setObjectName("saveBtn")
        self.verticalLayout_8.addWidget(self.saveBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #333333;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.imgBtn = QtWidgets.QPushButton(self.frame_3)
        self.imgBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.imgBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.imgBtn.setStyleSheet("border-image: url(:/img/fileIcon2.png);\n"
"background-color: transparent;")
        self.imgBtn.setText("")
        self.imgBtn.setObjectName("imgBtn")
        self.horizontalLayout_3.addWidget(self.imgBtn)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit.setToolTip("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像风格转换系统"))
        self.label.setText(_translate("MainWindow", "图像风格迁移系统"))
        self.label_4.setText(_translate("MainWindow", "By IvoExec"))
        self.groupBox.setTitle(_translate("MainWindow", "原图"))
        self.groupBox_2.setTitle(_translate("MainWindow", "风格转换图"))
        self.label_2.setText(_translate("MainWindow", "选择风格"))
        self.chageBtn.setText(_translate("MainWindow", "风格转换"))
        self.saveBtn.setText(_translate("MainWindow", "保存图片"))
        self.label_3.setText(_translate("MainWindow", "图片载入"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请选择一张图片"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.actionopen.setText(_translate("MainWindow", "图片载入"))
        self.action.setText(_translate("MainWindow", "保存图片"))
import resources_rc
